In [1]:
import numpy as np
import tensorflow as tf
tf.enable_eager_execution()
img = tf.reshape(np.arange(2*4*3), (2,4,3))

In [2]:
print(img)

tf.Tensor(
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]], shape=(2, 4, 3), dtype=int64)


In [3]:
print(tf.reverse(img, [-1]))

tf.Tensor(
[[[ 2  1  0]
  [ 5  4  3]
  [ 8  7  6]
  [11 10  9]]

 [[14 13 12]
  [17 16 15]
  [20 19 18]
  [23 22 21]]], shape=(2, 4, 3), dtype=int64)


In [1]:
print('grad'+str(1))

grad1
